import {
  Activity,
  BarChart3,
  BookOpen,
  Brain,
  Camera,
  Car,
  Cloud,
  Compass,
  CreditCard,
  Database,
  FileBarChart,
  FileText,
  Hash,
  Heart,
  History,
  Landmark,
  Layers,
  Lock,
  Map as MapIcon,
  MapPin,
  Network,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Users,
  Zap,
} from "lucide-react";
import type { ComponentType } from "react";
import type { SkillGroupId } from "@/i18n/content";

export const ZONE_ICONS: Record<string, ComponentType<{ size?: number; className?: string }>> = {
  "map-pin": MapPin,
  map: MapIcon,
  compass: Compass,
  activity: Activity,
  hash: Hash,
  car: Car,
  "file-text": FileText,
  lock: Lock,
  landmark: Landmark,
  "shield-check": ShieldCheck,
  shield: Shield,
  history: History,
  "bar-chart": BarChart3,
  users: Users,
  server: Server,
  smartphone: Smartphone,
  "credit-card": CreditCard,
  zap: Zap,
  network: Network,
  "file-bar-chart": FileBarChart,
  brain: Brain,
  camera: Camera,
  settings: Settings,
  heart: Heart,
  "book-open": BookOpen,
  sparkles: Sparkles,
  layers: Layers,
  database: Database,
  cloud: Cloud,
};

export const SKILL_GROUP_ICON_KEYS: Record<SkillGroupId, string> = {
  backend: "layers",
  frontend: "brain",
  data: "database",
  maps: "map",
  devops: "cloud",
  legacy: "file-bar-chart",
  ai: "sparkles",
};
